### ISSUE TITLE
Allow custom port for MYSQL in .env file

### ISSUE THREAD

**Issue by ofrei** [norment/redcap#11]
Allow custom port for MYSQL in .env file. The ports for both redcap and phpmyadmin now can be configured, so if we also allow configuring mysql port then I'm sure we can run two independent instances of redcap on the same host - it would be a nice feature to have.

However we do refer to ``database`` in several places as a host name for MYSQL database (see the code snippet below); I'm wondering if we have two instances of the same dockercompose file running (but with differently configured .env file) will each PHPMYADMIN and REDCAP webserver instances talk to the right instance of the MYSQL DATABASE? 
```
    database:            # <- that's hard-coded (as it should be, I think); what if we have two instances running - will this work?
        image: mysql
        restart: always
        env_file: .env
        volumes:
            - redcap_mysql_datavolume:/var/lib/mysql
```

**Comment by juuf** [comment]
Works with the current setup as you said
