### ISSUE TITLE
Add 'container_name' variable to all services in docker-compose.yml

### ISSUE THREAD

**Issue by ofrei** [norment/redcap#12]
Since we ask user to run some commands like this
``podman cp $REDCAPDIR/redcap redcap_webserver_1:/var/www/html/``
it's best to have a well-defined container name  in docker-compose.yml.

**Comment by ofrei** [comment]
Let's do as in https://github.com/123andy/redcap-docker-compose/blob/master/rdc/docker-compose.yml#L4C5-L4C19 , i.e. define ``DOCKER_PREFIX`` env variable in .env file and use it as a prefix for ``container_name``

**Comment by ofrei** [comment]
Let's also add ``network`` following https://github.com/123andy/redcap-docker-compose/blob/master/rdc/docker-compose.yml#L4C5-L4C19

**Comment by ofrei** [comment]
And volumes :)

**Comment by juuf** [comment]
@ofrei Is added and works

**Comment by ofrei** [comment]
@juuf excellent! just one thing I spotted, best to revert  '            - /Users/ju/Downloads/redcap/test:/backup' change in the docker-compose file

**Comment by juuf** [comment]
Good luck totally forgot that :)
