### ISSUE TITLE
/var/www/html/redcap/temp not writable on the server

### ISSUE THREAD

**Issue by ofrei** [norment/redcap#18]
<img width="1106" alt="image" src="https://github.com/norment/redcap/assets/13171449/ddfd422b-621d-4bd0-892d-bede9612ae3c">
Did this change after upgrade to new deployment procedure?

**Comment by ofrei** [comment]
To reproduce, just click on the"Dictionary" link of a project:
<img width="287" alt="image" src="https://github.com/norment/redcap/assets/13171449/9f2e7540-ec20-4f1a-8a22-bb06a23c309c">

**Comment by juuf** [comment]
The issue due to not applying chmod recursevly (```chmod -R 777```) to the redcap directory before moving it into the container
