### ISSUE TITLE
cleaner name and versions for images & containers

### ISSUE THREAD

**Issue by ofrei** [norment/redcap#2]
![image](https://user-images.githubusercontent.com/13171449/133987263-4a54a3ce-de4a-4418-99d1-47de4db9175f.png)
Let's discuss what names to use

**Comment by Sandeek** [comment]
Find how to version containers. Especially for webserver_redcap.tar.gz - this needs to have redcap version in the file name. But also within docker, instead of ``:latest`` we could have some versions. Less important for PHP & DB, but eventually those also might be updated.
